### ISSUE TITLE
Structural changes

### ISSUE THREAD

**Issue by jvcasillas** [learnB4SS/slides#2]
@stefanocoretta I'm going to change the structure of the main branch a bit to get ready for adding content. This shouldn't matter at all, but this is just a heads up in case you want to bring in those changes to your branch (once I've done them). I'll let you know here. 👍🏼

**Comment by stefanocoretta** [comment]
Would be a good idea to add renv too (which I did on my branch without really thinking...)

**Comment by jvcasillas** [comment]
Saw that and I agree. Will it cause issues for you to merge that into main? No, right?

**Comment by stefanocoretta** [comment]
Not that I can foreseen!

**Comment by stefanocoretta** [comment]
I am not sure how to use the current structure. Couldn't the `index.Rmd` file be
in the project root, rather than in the `ex/` directory? I think it would be
easier for users to just get everything in the root without having to go to
other folders.

It seems that the `assets/` and `js/` dirs in the root are not really used by
the presentation file, is this correct?

**Comment by stefanocoretta** [comment]
Ah, sorry, I saw now the new folders... I guess you can give us a tour today at the meeting! :)
